teleop:
  delta_arm_command:
    type: topic
    message_type: uwrt_arm_msgs/UWRTArmCommand
    topic_name: jog_server/delta_arm_cmds
    axis_mappings:
      -
        axis: 0
        target: turntable_command
        scale: 1.0
        offset: 0
      -
        axis: 1
        target: shoulder_command
        scale: 1.0
        offset: 0
      -
        axis: 7
        target: elbow_command
        scale: 1.0
        offset: 0
      -
        axis: 6
        target: wrist_roll_command
        scale: 1.0
        offset: 0
      -
        axis: 4
        target: wrist_pitch_command
        scale: 1.0
        offset: 0
